'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, Eye, Pencil, RotateCcw, Shuffle, Download, Trash2, X, LoaderCircle, Trophy, ExternalLink, FileText } from 'lucide-react';
import { LoginGate, useAuth } from './app-shell';
import { getSupabase, friendlyError } from '../lib/supabase';
import { demoDeck } from '../lib/demo';
import { cardSchema, youtubeUrl } from '../lib/validation';

export function StudyPage({id}){
  const {user}=useAuth(),[deck,setDeck]=useState(()=>id==='demo'?demoDeck:null),[error,setError]=useState(''),[loading,setLoading]=useState(id!=='demo');
  useEffect(()=>{
    if(id==='demo'){setDeck(demoDeck);setLoading(false);return;}
    if(!user){setDeck(null);return;}let active=true;setLoading(true);setError('');
    getSupabase().from('decks').select('*, cards(*, card_progress(*))').eq('id',id).maybeSingle().then(({data,error})=>{if(!active)return;if(error)setError(friendlyError(error));else if(!data)setError('Kumpulan kartu tidak ditemukan atau bukan milik akun ini.');else if(data.status!=='ready')setError('Kartu belum siap. Periksa statusnya di Kartu Saya.');else setDeck({...data,cards:data.cards.sort((a,b)=>a.position-b.position)});setLoading(false);});
    return()=>{active=false;};
  },[id,user?.id]);
  const content=loading?<div className="empty-state"><LoaderCircle className="spin"/><p>Membuka flashcard…</p></div>:error?<div className="empty-state"><p className="notice error" role="alert">{error}</p><Link className="button secondary" href="/belajar">Kembali ke Kartu Saya</Link></div>:deck?<StudySession key={`${id}-${user?.id||'guest'}`} initialDeck={deck} demo={id==='demo'}/>:null;
  return <main id="main" className="page-width workspace study-workspace">{id==='demo'?content:<LoginGate>{content}</LoginGate>}</main>;
}

function StudySession({initialDeck,demo}){
  const {user}=useAuth();
  const [cards,setCards]=useState(initialDeck.cards),[queue,setQueue]=useState(initialDeck.cards.map(c=>c.id)),[index,setIndex]=useState(()=>{const next=initialDeck.cards.findIndex(c=>!c.card_progress?.length);return Math.max(0,next);}),[revealed,setRevealed]=useState(false),[done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState(false),[draft,setDraft]=useState({question:'',answer:'',reference:''}),[sources,setSources]=useState(null),[sourceBusy,setSourceBusy]=useState(false);
  const [progress,setProgress]=useState(()=>Object.fromEntries(initialDeck.cards.filter(c=>c.card_progress?.[0]).map(c=>[c.id,c.card_progress[0]])));
  const current=cards.find(c=>c.id===queue[index]);
  const known=cards.filter(c=>progress[c.id]?.rating==='known').length;
  const unsure=cards.filter(c=>progress[c.id]?.rating==='unsure').length;
  const again=cards.filter(c=>progress[c.id]?.rating==='again').length;
  const unrated=cards.length-known-unsure-again;
  const rate=useCallback(async rating=>{
    if(!current||!revealed||busy||editing||done)return;
    setBusy(true);setError('');
    const next={card_id:current.id,owner_id:user?.id,rating,reviews:(progress[current.id]?.reviews||0)+1,reviewed_at:new Date().toISOString()};
    try {
      if(!demo){const {error}=await getSupabase().from('card_progress').upsert(next,{onConflict:'card_id,owner_id'});if(error)throw error;}
      setProgress(previous=>({...previous,[current.id]:next}));setRevealed(false);
      if(index>=queue.length-1)setDone(true);else setIndex(index+1);
    }catch(e){setError(friendlyError(e));}finally{setBusy(false);}
  },[current,revealed,busy,editing,done,user?.id,progress,demo,index,queue.length]);
  useEffect(()=>{
    function key(event){if(event.repeat||['INPUT','TEXTAREA','SELECT','BUTTON','A'].includes(event.target.tagName)||document.querySelector('dialog[open]')||editing||done||busy)return;
      if(event.code==='Space'){event.preventDefault();setRevealed(v=>!v);}
      if(revealed&&['1','2','3'].includes(event.key)){event.preventDefault();rate({1:'again',2:'unsure',3:'known'}[event.key]);}
    }window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);
  },[rate,revealed,editing,done,busy]);
  function restart(mode){let ids=cards.filter(c=>mode!=='difficult'||progress[c.id]?.rating!=='known').map(c=>c.id);if(mode==='shuffle'){for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]];}}setQueue(ids);setIndex(0);setRevealed(false);setDone(ids.length===0);setEditing(false);setError('');}
  function navigate(delta){setIndex(i=>i+delta);setRevealed(false);setEditing(false);setError('');}
  function exportDeck(){const json=JSON.stringify({version:1,title:initialDeck.title,cards:cards.map(({question,answer,reference})=>({question,answer,reference}))},null,2);const url=URL.createObjectURL(new Blob([json],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='recall-flashcards.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function saveCard(event){event.preventDefault();const checked=cardSchema.safeParse(draft);if(!checked.success){setError('Pertanyaan minimal 3 karakter dan jawaban tidak boleh kosong.');return;}setBusy(true);setError('');try{const {error}=await getSupabase().from('cards').update(checked.data).eq('id',current.id);if(error)throw error;setCards(previous=>previous.map(c=>c.id===current.id?{...c,...checked.data}:c));setEditing(false);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  async function deleteCard(){if(!window.confirm('Hapus kartu ini beserta progresnya?'))return;setBusy(true);setError('');try{const {error}=await getSupabase().from('cards').delete().eq('id',current.id);if(error)throw error;const remaining=cards.filter(c=>c.id!==current.id);setCards(remaining);const ids=queue.filter(id=>id!==current.id);setQueue(ids);setIndex(Math.min(index,Math.max(0,ids.length-1)));setRevealed(false);setEditing(false);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  async function showSources(){if(sources){setSources(null);return;}setSourceBusy(true);setError('');try{const db=getSupabase();const {data,error}=await db.from('source_files').select('*').eq('deck_id',initialDeck.id).order('position');if(error)throw error;const links=await Promise.all((data||[]).map(async s=>{if(s.url)return {...s,href:youtubeUrl(s.url)};const {data,error}=await db.storage.from('materials').createSignedUrl(s.path,120);if(error)throw error;return {...s,href:data.signedUrl};}));setSources(links);}catch(e){setError(friendlyError(e));}finally{setSourceBusy(false);}}
  return <><div className="study-top"><Link className="back-link" href="/belajar"><ArrowLeft size={17}/> Kartu Saya</Link><div className="toolbar-buttons"><button className="button small secondary" onClick={()=>restart('shuffle')} disabled={busy||!cards.length}><Shuffle size={16}/> Acak</button><button className="button small secondary" onClick={exportDeck} disabled={!cards.length}><Download size={16}/> Ekspor</button></div></div><div className="study-heading"><p className="eyebrow">{demo?'COBA ACTIVE RECALL':'SATU SESI, SATU LANGKAH MAJU'}</p><h1>{initialDeck.title}</h1><p>{demo?'Ini kartu contoh. Progres sesi contoh tidak disimpan.':'Coba jawab dalam pikiran atau tulis jawabanmu sebelum membuka kartu.'}</p></div>
    {error?<div className="notice error" role="alert">{error}</div>:null}
    {!cards.length?<div className="empty-state"><h2>Kumpulan ini sudah kosong.</h2><Link className="button" href="/materi">Buat kartu baru</Link></div>:done?<section className="session-summary"><div className="summary-icon"><Trophy size={34}/></div><p className="eyebrow">SESI SELESAI</p><h2>Selangkah lebih paham.</h2><p>Ini pemahamanmu saat ini. Kartu yang belum dikuasai bisa kamu ulangi.</p><div className="summary-stats"><div><strong>{known}</strong><span>Sudah paham</span></div><div><strong>{unsure+again}</strong><span>Perlu diulang</span></div><div><strong>{unrated}</strong><span>Belum dinilai</span></div></div><div className="summary-actions"><button className="button" onClick={()=>restart('difficult')} disabled={known===cards.length}><RotateCcw size={18}/> Ulang kartu sulit</button><button className="button secondary" onClick={()=>restart('all')}>Ulang semua kartu</button></div><Link className="text-link" href={demo?'/materi':'/belajar'}>{demo?'Buat flashcard dari materimu':'Kembali ke Kartu Saya'} <ArrowRight size={17}/></Link></section>:current?<div className="study-area"><div className="study-progress"><span>Kartu <strong>{index+1}</strong> dari {queue.length}</span><span>{known} / {cards.length} sudah paham</span></div><div className="progress-track session-track"><span style={{width:`${index/queue.length*100}%`}}/></div><article className={`flashcard ${revealed?'answer-visible':''}`} aria-live="polite"><div className="flashcard-top"><span className="mini-chip">{editing?'EDIT KARTU':revealed?'JAWABAN':'PERTANYAAN'}</span>{!demo?<div className="toolbar-buttons"><button className="icon-button" aria-label="Edit kartu" disabled={busy} onClick={()=>{setDraft({question:current.question,answer:current.answer,reference:current.reference});setEditing(true);}}><Pencil size={17}/></button><button className="icon-button" aria-label="Hapus kartu" disabled={busy} onClick={deleteCard}><Trash2 size={17}/></button></div>:null}</div>
    {editing?<form className="edit-card-form" onSubmit={saveCard}><label>Pertanyaan<textarea required minLength={3} maxLength={1000} value={draft.question} onChange={e=>setDraft({...draft,question:e.target.value})}/></label><label>Jawaban<textarea required maxLength={3000} value={draft.answer} onChange={e=>setDraft({...draft,answer:e.target.value})}/></label><label>Referensi<input maxLength={200} value={draft.reference} onChange={e=>setDraft({...draft,reference:e.target.value})}/></label><div className="toolbar-buttons"><button className="button small" disabled={busy}>Simpan perubahan</button><button type="button" className="button small secondary" onClick={()=>setEditing(false)} disabled={busy}><X size={16}/> Batal</button></div></form>:<><div className="flashcard-content">{revealed?<><p className="question-context">{current.question}</p><h2 className="flashcard-answer">{current.answer}</h2></>:<><span className="card-number">{String(index+1).padStart(2,'0')}</span><h2>{current.question}</h2><p>Ambil waktu sebentar. Apa yang kamu ingat?</p></>}</div>{revealed?<p className="card-reference">{current.reference||'Berdasarkan materi yang kamu kirim.'}</p>:<button className="button reveal-button" onClick={()=>setRevealed(true)}><Eye size={18}/> Tampilkan jawaban</button>}</>}
    </article>{!editing?<div className="rating-area"><p>{revealed?'Seberapa yakin dengan jawabanmu?':'Jawab dulu, lalu buka jawaban untuk menilai pemahamanmu.'}</p><div className="rating-buttons"><button className="rating again" disabled={!revealed||busy} onClick={()=>rate('again')}><RotateCcw size={17}/><span>Belum paham</span><kbd>1</kbd></button><button className="rating unsure" disabled={!revealed||busy} onClick={()=>rate('unsure')}><span>Ragu</span><kbd>2</kbd></button><button className="rating known" disabled={!revealed||busy} onClick={()=>rate('known')}><Check size={17}/><span>Sudah paham</span><kbd>3</kbd></button></div>{busy?<span className="save-status" role="status">Menyimpan progres…</span>:null}</div>:null}<div className="study-navigation"><button className="text-link" disabled={index===0||busy} onClick={()=>navigate(-1)}><ArrowLeft size={17}/> Sebelumnya</button><span className="keyboard-hint">Spasi: buka / tutup jawaban</span><button className="text-link" disabled={index===queue.length-1||busy} onClick={()=>navigate(1)}>Berikutnya <ArrowRight size={17}/></button></div></div>:null}
    {!demo?<div className="source-section"><button className="text-link" onClick={showSources} disabled={sourceBusy}>{sourceBusy?<LoaderCircle size={16} className="spin"/>:<FileText size={16}/>} {sources?'Tutup materi sumber':'Lihat materi sumber'}</button>{sources?<div className="source-links">{sources.length?sources.map(s=>s.href?<a href={s.href} key={s.id} target="_blank" rel="noopener noreferrer">{s.name} <ExternalLink size={14}/></a>:null):<span>Tidak ada file sumber untuk kartu impor.</span>}</div>:null}</div>:null}
  </>;
}
